Repository exasol/project-keeper, pull requests merged in 2021-01, with the labels that each got.

#57 #55: Fixed CVE-2020-8908 by excluding guava dependency
  doc/changes/changelog.md
  doc/changes/changes_0.5.0.md
  pom.xml
  src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java
  src/test/resources/test_project/pom.xml
Labels: bug

#59 #52: Changed behavior to not force user to create a changes file if version contains a snapshot tag
  doc/changes/changes_0.5.0.md
  src/main/java/com/exasol/projectkeeper/validators/ChangelogValidator.java
  src/test/java/com/exasol/projectkeeper/validators/ChangelogValidatorTest.java
Labels: feature

#62 * #61: Updated the template for Maven Central release workflow.
  .github/workflows/maven_central_release.yml
  doc/changes/changes_0.5.0.md
  src/main/resources/templates/maven_central/require_exact/.github/workflows/maven_central_release.yml
Labels: refactoring

#63 Refactored to use error message builder
  .github/workflows/maven_central_release.yml
  doc/changes/changes_0.5.0.md
  pom.xml
  src/main/java/com/exasol/projectkeeper/ProjectKeeperModule.java
  src/main/java/com/exasol/projectkeeper/ProjectKeeperVerifyMojo.java
  src/main/java/com/exasol/projectkeeper/validators/ChangelogValidator.java
  src/main/java/com/exasol/projectkeeper/validators/files/ProjectFilesValidator.java
  src/main/java/com/exasol/projectkeeper/validators/pom/AbstractPomValidator.java
  src/main/java/com/exasol/projectkeeper/validators/pom/PomFileIO.java
  src/main/java/com/exasol/projectkeeper/validators/pom/dependencies/AbstractDependencyValidator.java
  src/main/java/com/exasol/projectkeeper/validators/pom/plugin/AbstractPluginPomValidator.java
  src/main/java/com/exasol/xpath/XPathErrorHandlingWrapper.java
  src/main/resources/templates/maven_central/require_exact/.github/workflows/maven_central_release.yml
  src/test/java/com/exasol/projectkeeper/AbstractProjectKeeperMojoTest.java
  src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java
  src/test/java/com/exasol/projectkeeper/validators/ChangelogValidatorTest.java
  src/test/java/com/exasol/projectkeeper/validators/files/ProjectFilesValidatorTest.java
  src/test/java/com/exasol/projectkeeper/validators/pom/PomFileIOTest.java
  src/test/java/com/exasol/projectkeeper/validators/pom/PomTesting.java
  src/test/java/com/exasol/projectkeeper/validators/pom/dependencies/JacocoAgentDependencyValidatorTest.java
  src/test/java/com/exasol/projectkeeper/validators/pom/plugin/AbstractMavenPluginPomValidatorTest.java
  src/test/java/com/exasol/projectkeeper/validators/pom/plugin/JacocoPluginPomValidatorTest.java
  src/test/java/com/exasol/projectkeeper/validators/pom/plugin/VersionMavenPluginPomValidatorTest.java
Labels: refactoring

#64 #46: Refactored integration tests
  doc/changes/changes_0.5.0.md
  pom.xml
  src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java
Labels: refactoring
