Repository exasol/project-keeper, pull requests merged in 2022-04, with the labels that each got.

#275 feature/73 Added license to generated pom
  LICENSE
  dependencies.md
  maven-project-crawler/pk_generated_parent.pom
  project-keeper-maven-plugin/pk_generated_parent.pom
  project-keeper-maven-plugin/src/test/java/com/exasol/projectkeeper/plugin/ProjectKeeperMojoIT.java
  project-keeper/error_code_config.yml
  project-keeper/pk_generated_parent.pom
  project-keeper/src/main/java/com/exasol/projectkeeper/LicenseNameReader.java
  project-keeper/src/main/java/com/exasol/projectkeeper/ProjectKeeper.java
  project-keeper/src/main/java/com/exasol/projectkeeper/RepoInfo.java
  project-keeper/src/main/java/com/exasol/projectkeeper/config/ProjectKeeperConfig.java
  project-keeper/src/main/java/com/exasol/projectkeeper/config/ProjectKeeperConfigReader.java
  project-keeper/src/main/java/com/exasol/projectkeeper/validators/pom/PomFileGenerator.java
  project-keeper/src/main/java/com/exasol/projectkeeper/validators/pom/PomFileValidator.java
  project-keeper/src/main/resources/LICENSE-template
  project-keeper/src/test/java/com/exasol/projectkeeper/LicenseNameReaderTest.java
  project-keeper/src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java
  project-keeper/src/test/java/com/exasol/projectkeeper/config/ProjectKeeperConfigReaderTest.java
  project-keeper/src/test/java/com/exasol/projectkeeper/config/ProjectKeeperConfigWriter.java
  project-keeper/src/test/java/com/exasol/projectkeeper/validators/pom/PomFileGeneratorTest.java
  project-keeper/src/test/java/com/exasol/projectkeeper/validators/pom/PomFileValidatorTest.java
  shared-model-classes/pk_generated_parent.pom
  shared-model-classes/src/main/java/com/exasol/projectkeeper/shared/repository/GitRepository.java
Labels: feature

#283 Bug/281 remove surefire excludes
  doc/changes/changes_2.3.0.md
  maven-project-crawler/pk_generated_parent.pom
  project-keeper-maven-plugin/pk_generated_parent.pom
  project-keeper/pk_generated_parent.pom
  project-keeper/src/main/resources/maven_templates/maven-failsafe-plugin.xml
  project-keeper/src/main/resources/maven_templates/maven-surefire-plugin.xml
  shared-model-classes/pk_generated_parent.pom
Labels: bug

#291 feature/290: Added module for native_image
  README.md
  doc/changes/changes_2.3.1.md
  doc/developers_guide/building_a_native_image_project.md
  doc/developers_guide/preparing_a_project_for_native_image_builds.md
  maven-project-crawler/pk_generated_parent.pom
  project-keeper-maven-plugin/pk_generated_parent.pom
  project-keeper/error_code_config.yml
  project-keeper/pk_generated_parent.pom
  project-keeper/src/main/java/com/exasol/projectkeeper/ProjectKeeperModule.java
  project-keeper/src/main/java/com/exasol/projectkeeper/validators/ReadmeFileValidator.java
  project-keeper/src/main/java/com/exasol/projectkeeper/validators/files/FileTemplateFromResource.java
  project-keeper/src/main/java/com/exasol/projectkeeper/validators/files/FileTemplatesFactory.java
  project-keeper/src/main/java/com/exasol/projectkeeper/validators/pom/PomFileGenerator.java
  project-keeper/src/main/resources/maven_templates/maven-failsafe-plugin.xml
  project-keeper/src/main/resources/maven_templates/maven-surefire-plugin.xml
  project-keeper/src/main/resources/maven_templates/native-image-maven-plugin.xml
  project-keeper/src/main/resources/templates/.github/workflows/ci-build-native-build.yml
  project-keeper/src/main/resources/templates/src/main/reflect-config.json
  project-keeper/src/test/java/com/exasol/projectkeeper/validators/ReadmeFileValidatorTest.java
  project-keeper/src/test/java/com/exasol/projectkeeper/validators/files/FileTemplatesFactoryTest.java
  project-keeper/src/test/java/com/exasol/projectkeeper/validators/pom/PomFileGeneratorTest.java
  release.sh
  shared-model-classes/pk_generated_parent.pom
Labels: feature

#294 Pin version of link checker
  .github/workflows/broken_links_checker.yml
  .github/workflows/ci-build-next-java.yml
  .github/workflows/ci-build.yml
  .github/workflows/dependencies_check.yml
  .github/workflows/release_droid_prepare_original_checksum.yml
  .github/workflows/release_droid_print_quick_checksum.yml
  .github/workflows/release_droid_release_on_maven_central.yml
  .github/workflows/release_droid_upload_github_release_assets.yml
  .github/workflows/test_linux_build_on_windows.yml
  .github/workflows/test_on_windows.yml
  README.md
  doc/changes/changes_2.3.1.md
  parent-pom/pom.xml
  project-keeper/src/main/resources/templates/.github/workflows/broken_links_checker.yml
  project-keeper/src/main/resources/templates/.github/workflows/ci-build-native-build.yml
  project-keeper/src/main/resources/templates/.github/workflows/ci-build-next-java.yml
  project-keeper/src/main/resources/templates/.github/workflows/ci-build.yml
  project-keeper/src/main/resources/templates/.github/workflows/dependencies_check.yml
  project-keeper/src/main/resources/templates/.github/workflows/release_droid_prepare_original_checksum.yml
  project-keeper/src/main/resources/templates/.github/workflows/release_droid_print_quick_checksum.yml
  project-keeper/src/main/resources/templates/.github/workflows/release_droid_release_on_maven_central.yml
  project-keeper/src/main/resources/templates/.github/workflows/release_droid_upload_github_release_assets.yml
Labels: source:exasol
